### ISSUE TITLE
Gookit/color dependency missing

### ISSUE THREAD

**Issue by daydr3am3r** [cybercdh/hacks#2]
See subject. Binary seems to require it. Should be at minimum listed as a dependency. Thank you for this tool!

$ go run main.go sfc
main.go:11:2: cannot find package "github.com/gookit/color" in any of:
        c:\go\src\github.com\gookit\color (from $GOROOT)
        C:\Users\dreamer\go\src\github.com\gookit\color (from $GOPATH)

**Comment by mrxinu** [comment]
@cybercdh If you do a `go mod init` and then commit the go.mod and go.sum files it'll automatically grab those dependencies on compile.

**Comment by cybercdh** [comment]
go.mod added, hopefully helps :)

**Comment by cybercdh** [comment]
I'll likely move this code to its own repo, but for now closing this issue as resolved
